baseURL = "/"
languageCode = "en-gb"
title = "EleutherAI"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "../data/research"
    target = "data/research"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "../assets/eleutherai-logo.svg"
    target = "static/assets/eleutherai-logo.svg"
